import React from 'react';
import Head from 'next/head';
import Layout from '../layout/Layout';
import Hero from '../components/Hero';
import SocialMedias from '../components/SocialMedias';

export default function Home() {
  return (
    <>
      <Head>
        <title>AEGLO - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero img="home_banner.jpeg" title="AEGLO" subtitle={"Association des étudiants et étudiantes en\ngénie logiciel de l'Université Laval"}>
          <SocialMedias direction="row" color="white" />
        </Hero>
      </Layout>
    </>
  );
}
