import React from 'react';
import Head from 'next/head';
import { Box } from '@chakra-ui/react';
import NavBar from '../components/NavBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>AEGLO - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Box bgColor="blue" h="2000px" />
    </>
  );
}
